/**
 * Pino Structured Logging Configuration (Winston replacement)
 * Provides high-performance structured logging with automatic request context
 */

import { Params } from 'nestjs-pino';

export const pinoLoggerConfig: Params = {
  pinoHttp: {
    level: process.env['LOG_LEVEL'] || 'info',

    // Development: Pretty print with colors
    // Production: JSON output for log aggregation
    transport: process.env['NODE_ENV'] !== 'production' ? {
      target: 'pino-pretty',
      options: {
        colorize: true,
        translateTime: 'SYS:yyyy-mm-dd HH:MM:ss',
        ignore: 'pid,hostname',
        singleLine: false,
        messageFormat: '{context} {msg}',
      },
    } : undefined,

    // Redact sensitive fields automatically
    redact: {
      paths: [
        'req.headers.authorization',
        'req.headers.cookie',
        'latitude',
        'longitude',
        'address',
        'user_id',
        'userId',
        'req.body.timelineData', // Don't log raw Timeline JSON
      ],
      censor: '[REDACTED]',
    },

    // Custom serializers for better log structure
    serializers: {
      req: (req) => ({
        method: req.method,
        url: req.url,
        params: req.params,
        query: req.query,
        // Don't log request body in production (can be large)
        ...(process.env['NODE_ENV'] !== 'production' && { body: req.body }),
      }),
      res: (res) => ({
        statusCode: res.statusCode,
      }),
      err: (err) => ({
        type: err.type,
        message: err.message,
        stack: err.stack,
        code: err.code,
      }),
    },

    // Auto-log all HTTP requests
    autoLogging: {
      ignore: (req) => req.url === '/health', // Don't log health checks
    },

    // Custom log levels for different contexts
    customLogLevel: (req, res, err) => {
      if (res.statusCode >= 400 && res.statusCode < 500) {
        return 'warn';
      } else if (res.statusCode >= 500 || err) {
        return 'error';
      }
      return 'info';
    },

    // Add custom properties to every log
    customProps: (req: any) => ({
      context: 'ImportService',
      userId: req.user?.id || req.user?.sub,
      requestId: req.id, // Auto-generated by pino-http
    }),
  },
};

/**
 * Create child logger with additional context for import operations
 * Usage: const logger = createImportLogger(pinoLogger, { fileName, stage });
 */
export function createImportLogger(
  pinoLogger: any,
  context: {
    fileName?: string;
    stage?: string;
    jobId?: string;
  }
) {
  return pinoLogger.child({
    ...context,
    context: 'ImportService',
  });
}
